//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace CampaignMasterWeb.GcmlWsReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICampaignMasterService", Namespace="http://tempuri.org/")]
    public partial class CampaignMasterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPlayerIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPlayerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPlayerCampaignsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCampaignInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFieldKoordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSektorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSektorListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUnitCollisionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommandsForUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback createNewCampaignOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPlayerToCampaignOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeCommandOperationCompleted;
        
        private System.Threading.SendOrPostCallback addUnitToFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback endRoundForPlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommandInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CampaignMasterService() {
            this.Url = global::CampaignMasterWeb.Properties.Settings.Default.CampaignMasterWeb_GcmlWs_CampaignMasterService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPlayerIdCompletedEventHandler getPlayerIdCompleted;
        
        /// <remarks/>
        public event getPlayerInfoCompletedEventHandler getPlayerInfoCompleted;
        
        /// <remarks/>
        public event getPlayerCampaignsCompletedEventHandler getPlayerCampaignsCompleted;
        
        /// <remarks/>
        public event getCampaignInfoCompletedEventHandler getCampaignInfoCompleted;
        
        /// <remarks/>
        public event getFieldKoordCompletedEventHandler getFieldKoordCompleted;
        
        /// <remarks/>
        public event getSektorCompletedEventHandler getSektorCompleted;
        
        /// <remarks/>
        public event getSektorListCompletedEventHandler getSektorListCompleted;
        
        /// <remarks/>
        public event getUnitCompletedEventHandler getUnitCompleted;
        
        /// <remarks/>
        public event getUnitCollisionsCompletedEventHandler getUnitCollisionsCompleted;
        
        /// <remarks/>
        public event getCommandsForUnitCompletedEventHandler getCommandsForUnitCompleted;
        
        /// <remarks/>
        public event createNewCampaignCompletedEventHandler createNewCampaignCompleted;
        
        /// <remarks/>
        public event addPlayerToCampaignCompletedEventHandler addPlayerToCampaignCompleted;
        
        /// <remarks/>
        public event executeCommandCompletedEventHandler executeCommandCompleted;
        
        /// <remarks/>
        public event addUnitToFieldCompletedEventHandler addUnitToFieldCompleted;
        
        /// <remarks/>
        public event endRoundForPlayerCompletedEventHandler endRoundForPlayerCompleted;
        
        /// <remarks/>
        public event getCommandInfoCompletedEventHandler getCommandInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getPlayerId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getPlayerId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playername) {
            object[] results = this.Invoke("getPlayerId", new object[] {
                        playername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPlayerIdAsync(string playername) {
            this.getPlayerIdAsync(playername, null);
        }
        
        /// <remarks/>
        public void getPlayerIdAsync(string playername, object userState) {
            if ((this.getPlayerIdOperationCompleted == null)) {
                this.getPlayerIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlayerIdOperationCompleted);
            }
            this.InvokeAsync("getPlayerId", new object[] {
                        playername}, this.getPlayerIdOperationCompleted, userState);
        }
        
        private void OngetPlayerIdOperationCompleted(object arg) {
            if ((this.getPlayerIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlayerIdCompleted(this, new getPlayerIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getPlayerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PlayerInfo getPlayerInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid) {
            object[] results = this.Invoke("getPlayerInfo", new object[] {
                        playerid});
            return ((PlayerInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getPlayerInfoAsync(string playerid) {
            this.getPlayerInfoAsync(playerid, null);
        }
        
        /// <remarks/>
        public void getPlayerInfoAsync(string playerid, object userState) {
            if ((this.getPlayerInfoOperationCompleted == null)) {
                this.getPlayerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlayerInfoOperationCompleted);
            }
            this.InvokeAsync("getPlayerInfo", new object[] {
                        playerid}, this.getPlayerInfoOperationCompleted, userState);
        }
        
        private void OngetPlayerInfoOperationCompleted(object arg) {
            if ((this.getPlayerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlayerInfoCompleted(this, new getPlayerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getPlayerCampaigns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getPlayerCampaigns([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid) {
            object[] results = this.Invoke("getPlayerCampaigns", new object[] {
                        playerid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getPlayerCampaignsAsync(string playerid) {
            this.getPlayerCampaignsAsync(playerid, null);
        }
        
        /// <remarks/>
        public void getPlayerCampaignsAsync(string playerid, object userState) {
            if ((this.getPlayerCampaignsOperationCompleted == null)) {
                this.getPlayerCampaignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlayerCampaignsOperationCompleted);
            }
            this.InvokeAsync("getPlayerCampaigns", new object[] {
                        playerid}, this.getPlayerCampaignsOperationCompleted, userState);
        }
        
        private void OngetPlayerCampaignsOperationCompleted(object arg) {
            if ((this.getPlayerCampaignsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlayerCampaignsCompleted(this, new getPlayerCampaignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getCampaignInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CampaignInfo getCampaignInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignId) {
            object[] results = this.Invoke("getCampaignInfo", new object[] {
                        campaignId});
            return ((CampaignInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getCampaignInfoAsync(string campaignId) {
            this.getCampaignInfoAsync(campaignId, null);
        }
        
        /// <remarks/>
        public void getCampaignInfoAsync(string campaignId, object userState) {
            if ((this.getCampaignInfoOperationCompleted == null)) {
                this.getCampaignInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCampaignInfoOperationCompleted);
            }
            this.InvokeAsync("getCampaignInfo", new object[] {
                        campaignId}, this.getCampaignInfoOperationCompleted, userState);
        }
        
        private void OngetCampaignInfoOperationCompleted(object arg) {
            if ((this.getCampaignInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCampaignInfoCompleted(this, new getCampaignInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getFieldKoord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public clsSektorKoordinaten getFieldKoord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getFieldKoord", new object[] {
                        campaignid});
            return ((clsSektorKoordinaten)(results[0]));
        }
        
        /// <remarks/>
        public void getFieldKoordAsync(string campaignid) {
            this.getFieldKoordAsync(campaignid, null);
        }
        
        /// <remarks/>
        public void getFieldKoordAsync(string campaignid, object userState) {
            if ((this.getFieldKoordOperationCompleted == null)) {
                this.getFieldKoordOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldKoordOperationCompleted);
            }
            this.InvokeAsync("getFieldKoord", new object[] {
                        campaignid}, this.getFieldKoordOperationCompleted, userState);
        }
        
        private void OngetFieldKoordOperationCompleted(object arg) {
            if ((this.getFieldKoordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldKoordCompleted(this, new getFieldKoordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getSektor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SektorInfo getSektor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] clsSektorKoordinaten sektorkoord) {
            object[] results = this.Invoke("getSektor", new object[] {
                        campaignid,
                        sektorkoord});
            return ((SektorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getSektorAsync(string campaignid, clsSektorKoordinaten sektorkoord) {
            this.getSektorAsync(campaignid, sektorkoord, null);
        }
        
        /// <remarks/>
        public void getSektorAsync(string campaignid, clsSektorKoordinaten sektorkoord, object userState) {
            if ((this.getSektorOperationCompleted == null)) {
                this.getSektorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSektorOperationCompleted);
            }
            this.InvokeAsync("getSektor", new object[] {
                        campaignid,
                        sektorkoord}, this.getSektorOperationCompleted, userState);
        }
        
        private void OngetSektorOperationCompleted(object arg) {
            if ((this.getSektorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSektorCompleted(this, new getSektorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getSektorList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getSektorList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getSektorList", new object[] {
                        campaignid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getSektorListAsync(string campaignid) {
            this.getSektorListAsync(campaignid, null);
        }
        
        /// <remarks/>
        public void getSektorListAsync(string campaignid, object userState) {
            if ((this.getSektorListOperationCompleted == null)) {
                this.getSektorListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSektorListOperationCompleted);
            }
            this.InvokeAsync("getSektorList", new object[] {
                        campaignid}, this.getSektorListOperationCompleted, userState);
        }
        
        private void OngetSektorListOperationCompleted(object arg) {
            if ((this.getSektorListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSektorListCompleted(this, new getSektorListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnitInfo getUnit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unitid) {
            object[] results = this.Invoke("getUnit", new object[] {
                        campaignid,
                        unitid});
            return ((UnitInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getUnitAsync(string campaignid, string unitid) {
            this.getUnitAsync(campaignid, unitid, null);
        }
        
        /// <remarks/>
        public void getUnitAsync(string campaignid, string unitid, object userState) {
            if ((this.getUnitOperationCompleted == null)) {
                this.getUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnitOperationCompleted);
            }
            this.InvokeAsync("getUnit", new object[] {
                        campaignid,
                        unitid}, this.getUnitOperationCompleted, userState);
        }
        
        private void OngetUnitOperationCompleted(object arg) {
            if ((this.getUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUnitCompleted(this, new getUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getUnitCollisions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
        public SektorInfo[] getUnitCollisions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getUnitCollisions", new object[] {
                        campaignid});
            return ((SektorInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getUnitCollisionsAsync(string campaignid) {
            this.getUnitCollisionsAsync(campaignid, null);
        }
        
        /// <remarks/>
        public void getUnitCollisionsAsync(string campaignid, object userState) {
            if ((this.getUnitCollisionsOperationCompleted == null)) {
                this.getUnitCollisionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUnitCollisionsOperationCompleted);
            }
            this.InvokeAsync("getUnitCollisions", new object[] {
                        campaignid}, this.getUnitCollisionsOperationCompleted, userState);
        }
        
        private void OngetUnitCollisionsOperationCompleted(object arg) {
            if ((this.getUnitCollisionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUnitCollisionsCompleted(this, new getUnitCollisionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getCommandsForUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib", IsNullable=false)]
        public CommandInfo[] getCommandsForUnit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unitid) {
            object[] results = this.Invoke("getCommandsForUnit", new object[] {
                        campaignid,
                        unitid});
            return ((CommandInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getCommandsForUnitAsync(string campaignid, string unitid) {
            this.getCommandsForUnitAsync(campaignid, unitid, null);
        }
        
        /// <remarks/>
        public void getCommandsForUnitAsync(string campaignid, string unitid, object userState) {
            if ((this.getCommandsForUnitOperationCompleted == null)) {
                this.getCommandsForUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommandsForUnitOperationCompleted);
            }
            this.InvokeAsync("getCommandsForUnit", new object[] {
                        campaignid,
                        unitid}, this.getCommandsForUnitOperationCompleted, userState);
        }
        
        private void OngetCommandsForUnitOperationCompleted(object arg) {
            if ((this.getCommandsForUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommandsForUnitCompleted(this, new getCommandsForUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/createNewCampaign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string createNewCampaign([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignname, int x, [System.Xml.Serialization.XmlIgnoreAttribute()] bool xSpecified, int y, [System.Xml.Serialization.XmlIgnoreAttribute()] bool ySpecified, int anzUnits, [System.Xml.Serialization.XmlIgnoreAttribute()] bool anzUnitsSpecified) {
            object[] results = this.Invoke("createNewCampaign", new object[] {
                        playerid,
                        campaignname,
                        x,
                        xSpecified,
                        y,
                        ySpecified,
                        anzUnits,
                        anzUnitsSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createNewCampaignAsync(string playerid, string campaignname, int x, bool xSpecified, int y, bool ySpecified, int anzUnits, bool anzUnitsSpecified) {
            this.createNewCampaignAsync(playerid, campaignname, x, xSpecified, y, ySpecified, anzUnits, anzUnitsSpecified, null);
        }
        
        /// <remarks/>
        public void createNewCampaignAsync(string playerid, string campaignname, int x, bool xSpecified, int y, bool ySpecified, int anzUnits, bool anzUnitsSpecified, object userState) {
            if ((this.createNewCampaignOperationCompleted == null)) {
                this.createNewCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateNewCampaignOperationCompleted);
            }
            this.InvokeAsync("createNewCampaign", new object[] {
                        playerid,
                        campaignname,
                        x,
                        xSpecified,
                        y,
                        ySpecified,
                        anzUnits,
                        anzUnitsSpecified}, this.createNewCampaignOperationCompleted, userState);
        }
        
        private void OncreateNewCampaignOperationCompleted(object arg) {
            if ((this.createNewCampaignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createNewCampaignCompleted(this, new createNewCampaignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/addPlayerToCampaign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPlayerToCampaign([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            this.Invoke("addPlayerToCampaign", new object[] {
                        playerid,
                        campaignid});
        }
        
        /// <remarks/>
        public void addPlayerToCampaignAsync(string playerid, string campaignid) {
            this.addPlayerToCampaignAsync(playerid, campaignid, null);
        }
        
        /// <remarks/>
        public void addPlayerToCampaignAsync(string playerid, string campaignid, object userState) {
            if ((this.addPlayerToCampaignOperationCompleted == null)) {
                this.addPlayerToCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPlayerToCampaignOperationCompleted);
            }
            this.InvokeAsync("addPlayerToCampaign", new object[] {
                        playerid,
                        campaignid}, this.addPlayerToCampaignOperationCompleted, userState);
        }
        
        private void OnaddPlayerToCampaignOperationCompleted(object arg) {
            if ((this.addPlayerToCampaignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPlayerToCampaignCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/executeCommand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void executeCommand([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, CommandInfo command) {
            this.Invoke("executeCommand", new object[] {
                        campaignid,
                        command});
        }
        
        /// <remarks/>
        public void executeCommandAsync(string campaignid, CommandInfo command) {
            this.executeCommandAsync(campaignid, command, null);
        }
        
        /// <remarks/>
        public void executeCommandAsync(string campaignid, CommandInfo command, object userState) {
            if ((this.executeCommandOperationCompleted == null)) {
                this.executeCommandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteCommandOperationCompleted);
            }
            this.InvokeAsync("executeCommand", new object[] {
                        campaignid,
                        command}, this.executeCommandOperationCompleted, userState);
        }
        
        private void OnexecuteCommandOperationCompleted(object arg) {
            if ((this.executeCommandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeCommandCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/addUnitToField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addUnitToField([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unit, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string targetsektor) {
            this.Invoke("addUnitToField", new object[] {
                        campaignid,
                        unit,
                        targetsektor});
        }
        
        /// <remarks/>
        public void addUnitToFieldAsync(string campaignid, string unit, string targetsektor) {
            this.addUnitToFieldAsync(campaignid, unit, targetsektor, null);
        }
        
        /// <remarks/>
        public void addUnitToFieldAsync(string campaignid, string unit, string targetsektor, object userState) {
            if ((this.addUnitToFieldOperationCompleted == null)) {
                this.addUnitToFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddUnitToFieldOperationCompleted);
            }
            this.InvokeAsync("addUnitToField", new object[] {
                        campaignid,
                        unit,
                        targetsektor}, this.addUnitToFieldOperationCompleted, userState);
        }
        
        private void OnaddUnitToFieldOperationCompleted(object arg) {
            if ((this.addUnitToFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addUnitToFieldCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/endRoundForPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void endRoundForPlayer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid) {
            this.Invoke("endRoundForPlayer", new object[] {
                        campaignid,
                        playerid});
        }
        
        /// <remarks/>
        public void endRoundForPlayerAsync(string campaignid, string playerid) {
            this.endRoundForPlayerAsync(campaignid, playerid, null);
        }
        
        /// <remarks/>
        public void endRoundForPlayerAsync(string campaignid, string playerid, object userState) {
            if ((this.endRoundForPlayerOperationCompleted == null)) {
                this.endRoundForPlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnendRoundForPlayerOperationCompleted);
            }
            this.InvokeAsync("endRoundForPlayer", new object[] {
                        campaignid,
                        playerid}, this.endRoundForPlayerOperationCompleted, userState);
        }
        
        private void OnendRoundForPlayerOperationCompleted(object arg) {
            if ((this.endRoundForPlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.endRoundForPlayerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getCommandInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommandInfo getCommandInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string commandId) {
            object[] results = this.Invoke("getCommandInfo", new object[] {
                        campaignid,
                        commandId});
            return ((CommandInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getCommandInfoAsync(string campaignid, string commandId) {
            this.getCommandInfoAsync(campaignid, commandId, null);
        }
        
        /// <remarks/>
        public void getCommandInfoAsync(string campaignid, string commandId, object userState) {
            if ((this.getCommandInfoOperationCompleted == null)) {
                this.getCommandInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommandInfoOperationCompleted);
            }
            this.InvokeAsync("getCommandInfo", new object[] {
                        campaignid,
                        commandId}, this.getCommandInfoOperationCompleted, userState);
        }
        
        private void OngetCommandInfoOperationCompleted(object arg) {
            if ((this.getCommandInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommandInfoCompleted(this, new getCommandInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class PlayerInfo {
        
        private string playerIdField;
        
        private string playerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string playerId {
            get {
                return this.playerIdField;
            }
            set {
                this.playerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string playerName {
            get {
                return this.playerNameField;
            }
            set {
                this.playerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class CommandInfo {
        
        private string actingUnitIdField;
        
        private string commandIdField;
        
        private string commandTypeField;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private string strInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string actingUnitId {
            get {
                return this.actingUnitIdField;
            }
            set {
                this.actingUnitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandId {
            get {
                return this.commandIdField;
            }
            set {
                this.commandIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commandType {
            get {
                return this.commandTypeField;
            }
            set {
                this.commandTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strInfo {
            get {
                return this.strInfoField;
            }
            set {
                this.strInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class UnitInfo {
        
        private string playerIdField;
        
        private string sektorIdField;
        
        private string unitIdField;
        
        private string unitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string playerId {
            get {
                return this.playerIdField;
            }
            set {
                this.playerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sektorId {
            get {
                return this.sektorIdField;
            }
            set {
                this.sektorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class SektorInfo {
        
        private string[] containedUnitIdsField;
        
        private string sektorIdField;
        
        private clsSektorKoordinaten sektorKoordinatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] containedUnitIds {
            get {
                return this.containedUnitIdsField;
            }
            set {
                this.containedUnitIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sektorId {
            get {
                return this.sektorIdField;
            }
            set {
                this.sektorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public clsSektorKoordinaten sektorKoordinaten {
            get {
                return this.sektorKoordinatenField;
            }
            set {
                this.sektorKoordinatenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class clsSektorKoordinaten {
        
        private int[] positionField;
        
        private int xField;
        
        private bool xFieldSpecified;
        
        private int yField;
        
        private bool yFieldSpecified;
        
        private int zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YSpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GenericCampaignMasterLib")]
    public partial class CampaignInfo {
        
        private string campaignIdField;
        
        private string campaignNameField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] playersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] players {
            get {
                return this.playersField;
            }
            set {
                this.playersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPlayerIdCompletedEventHandler(object sender, getPlayerIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlayerIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlayerIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPlayerInfoCompletedEventHandler(object sender, getPlayerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlayerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlayerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlayerInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlayerInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPlayerCampaignsCompletedEventHandler(object sender, getPlayerCampaignsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlayerCampaignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlayerCampaignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCampaignInfoCompletedEventHandler(object sender, getCampaignInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCampaignInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCampaignInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CampaignInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CampaignInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getFieldKoordCompletedEventHandler(object sender, getFieldKoordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldKoordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldKoordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsSektorKoordinaten Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsSektorKoordinaten)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getSektorCompletedEventHandler(object sender, getSektorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSektorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSektorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SektorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SektorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getSektorListCompletedEventHandler(object sender, getSektorListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSektorListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSektorListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getUnitCompletedEventHandler(object sender, getUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnitInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnitInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getUnitCollisionsCompletedEventHandler(object sender, getUnitCollisionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUnitCollisionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUnitCollisionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SektorInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SektorInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCommandsForUnitCompletedEventHandler(object sender, getCommandsForUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommandsForUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommandsForUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommandInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommandInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createNewCampaignCompletedEventHandler(object sender, createNewCampaignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createNewCampaignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createNewCampaignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addPlayerToCampaignCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void executeCommandCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addUnitToFieldCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void endRoundForPlayerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getCommandInfoCompletedEventHandler(object sender, getCommandInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommandInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommandInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommandInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommandInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591