//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampaignMasterWeb.GcmlWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICampaignMasterService", Namespace="http://tempuri.org/")]
    public partial class CampaignMasterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CampaignMasterService() {
            this.Url = "http://127.0.0.1:8080/CampaignMasterService.svc";
        }
        
        public CampaignMasterService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getPlayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getPlayer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playername) {
            object[] results = this.Invoke("getPlayer", new object[] {
                        playername});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPlayer(string playername, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPlayer", new object[] {
                        playername}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPlayer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getPlayerCampaigns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getPlayerCampaigns([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid) {
            object[] results = this.Invoke("getPlayerCampaigns", new object[] {
                        playerid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPlayerCampaigns(string playerid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPlayerCampaigns", new object[] {
                        playerid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetPlayerCampaigns(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getFieldKoord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getFieldKoord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getFieldKoord", new object[] {
                        campaignid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetFieldKoord(string campaignid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getFieldKoord", new object[] {
                        campaignid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetFieldKoord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getSektor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getSektor([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sektorkoord) {
            object[] results = this.Invoke("getSektor", new object[] {
                        campaignid,
                        sektorkoord});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSektor(string campaignid, string sektorkoord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSektor", new object[] {
                        campaignid,
                        sektorkoord}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSektor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getSektorList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getSektorList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getSektorList", new object[] {
                        campaignid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSektorList(string campaignid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSektorList", new object[] {
                        campaignid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetSektorList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getUnit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unitid) {
            object[] results = this.Invoke("getUnit", new object[] {
                        campaignid,
                        unitid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUnit(string campaignid, string unitid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUnit", new object[] {
                        campaignid,
                        unitid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetUnit(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getUnitCollisions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getUnitCollisions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            object[] results = this.Invoke("getUnitCollisions", new object[] {
                        campaignid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUnitCollisions(string campaignid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUnitCollisions", new object[] {
                        campaignid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetUnitCollisions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/getCommandsForUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getCommandsForUnit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unitid) {
            object[] results = this.Invoke("getCommandsForUnit", new object[] {
                        campaignid,
                        unitid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCommandsForUnit(string campaignid, string unitid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCommandsForUnit", new object[] {
                        campaignid,
                        unitid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndgetCommandsForUnit(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/createNewCampaign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string createNewCampaign([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fielddimension) {
            object[] results = this.Invoke("createNewCampaign", new object[] {
                        playerid,
                        fielddimension});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewCampaign(string playerid, string fielddimension, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewCampaign", new object[] {
                        playerid,
                        fielddimension}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcreateNewCampaign(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/addPlayerToCampaign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addPlayerToCampaign([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string playerid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid) {
            this.Invoke("addPlayerToCampaign", new object[] {
                        playerid,
                        campaignid});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddPlayerToCampaign(string playerid, string campaignid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addPlayerToCampaign", new object[] {
                        playerid,
                        campaignid}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddPlayerToCampaign(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/executeCommand", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void executeCommand([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string command) {
            this.Invoke("executeCommand", new object[] {
                        campaignid,
                        command});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexecuteCommand(string campaignid, string command, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("executeCommand", new object[] {
                        campaignid,
                        command}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndexecuteCommand(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICampaignMasterService/addUnitToField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addUnitToField([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string campaignid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string unit, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string targetsektor) {
            this.Invoke("addUnitToField", new object[] {
                        campaignid,
                        unit,
                        targetsektor});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddUnitToField(string campaignid, string unit, string targetsektor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addUnitToField", new object[] {
                        campaignid,
                        unit,
                        targetsektor}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddUnitToField(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
